const ADMIN_PRODUCTS_PER_PAGE = 6;
const USERS_PER_PAGE = 6;
const ADMIN_ORDER_PER_PAGE = 7;
const CATEGORY_PER_PAGE = 6;
const SHOP_PRODUCTS_PER_PAGE = 9;

module.exports = {
    ADMIN_PRODUCTS_PER_PAGE,
    USERS_PER_PAGE,
    ADMIN_ORDER_PER_PAGE,
    CATEGORY_PER_PAGE,
    SHOP_PRODUCTS_PER_PAGE
}
